a=input("Name:")
b=input("Class")
c=input("register number:")
d=input("Address:")
e=input("Mobile number:")
f=input("Blood Group:")
g=input("E-mail:")
h=input("Sex:")

print("is",a)
print("is",b)
print("is",c)
print("is",d)
print("is",e)
print("is",f)
print("is",g)
print("is",h)